services:
  - type: web
    name: shadownet
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OTX_API_KEY
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: OPENSKY_CLIENT_ID
        sync: false
      - key: OPENSKY_CLIENT_SECRET
        sync: false
      - key: AIS_STREAM_API_KEY
        sync: false
